"""OpenAI-backed chat orchestration for NIPS agents.

Yields typed event dicts that the Socket.IO router forwards to the client:
  - thought_chunk   : ephemeral reasoning text (emulated or empty for OpenAI)
  - tool_call_start : tool invocation began
  - tool_call_result: tool finished (with scored output preview)
  - assistant_chunk : final-answer text fragment
  - evidence_update : new evidence generated by a tool
  - done            : stream complete
  - error           : something went wrong
"""

from __future__ import annotations

import logging
import os
import uuid
import json
from typing import Any, AsyncIterator

from openai import AsyncOpenAI

from config import OPENAI_API_KEY, NIPS_MODEL_NAME
from nips.archetypes import ARCHETYPES
from nips.models import AgentInstance, ChatMessage, EvidenceUpdate
from nips.prompts import build_system_prompt
from nips.scoring import ScoredOutcome, score_tool_execution
from nips.tools import TOOL_DECLARATION_MAP, TOOL_EXECUTORS

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# OpenAI client (lazy singleton)
# ---------------------------------------------------------------------------

_client: AsyncOpenAI | None = None


def _get_client() -> AsyncOpenAI:
    global _client
    if _client is None:
        key = OPENAI_API_KEY
        if not key:
            raise RuntimeError(
                "OPENAI_API_KEY is not set. "
                "Update your .env file."
            )
        _client = AsyncOpenAI(api_key=key)
    return _client


# ---------------------------------------------------------------------------
# Build OpenAI tool declarations from archetype
# ---------------------------------------------------------------------------


def _build_openai_tools(agent: AgentInstance) -> list[dict[str, Any]]:
    """Return a list of OpenAI tool dictionaries for the agent's archetype."""
    archetype = ARCHETYPES[agent.archetype]
    tools = []
    for tool_name in archetype.allowed_tools:
        decl = TOOL_DECLARATION_MAP.get(tool_name)
        if not decl:
            continue
        
        # Simplify schema for OpenAI format
        tools.append({
            "type": "function",
            "function": {
                "name": decl["name"],
                "description": decl["description"],
                "parameters": decl["parameters"],
            }
        })

    return tools


# ---------------------------------------------------------------------------
# Convert chat history → OpenAI messages
# ---------------------------------------------------------------------------


def _history_to_messages(messages: list[ChatMessage]) -> list[dict[str, Any]]:
    """Convert stored chat messages to OpenAI message objects."""
    openai_msgs: list[dict[str, Any]] = []
    for msg in messages:
        if msg.role == "user":
            openai_msgs.append({"role": "user", "content": msg.content})
        elif msg.role == "assistant":
            data: dict[str, Any] = {"role": "assistant"}
            if msg.content:
                data["content"] = msg.content
            if msg.tool_calls:
                data["tool_calls"] = msg.tool_calls
            openai_msgs.append(data)
        elif msg.role == "tool" and msg.tool_name:
            openai_msgs.append({
                "role": "tool",
                "tool_call_id": msg.tool_call_id or f"call_{uuid.uuid4().hex[:12]}",
                "content": msg.content,
            })
    return openai_msgs


# ---------------------------------------------------------------------------
# Main streaming chat generator
# ---------------------------------------------------------------------------


async def stream_agent_chat(
    agent: AgentInstance,
    user_message: str,
    *,
    history: list[ChatMessage] | None = None,
    case_summary: str = "",
    node_context: str = "",
    known_evidence: list[EvidenceUpdate] | None = None,
    previous_findings: list[str] | None = None,
    funds: int = 0,
    pressure: float = 0.0,
) -> AsyncIterator[dict[str, Any]]:
    """Stream an OpenAI chat turn, yielding typed event dicts."""
    client = _get_client()
    archetype = ARCHETYPES[agent.archetype]

    system_prompt = build_system_prompt(
        agent,
        case_summary=case_summary,
        node_context=node_context,
        known_evidence=known_evidence,
        previous_findings=previous_findings,
        funds=funds,
        pressure=pressure,
        allowed_tool_names=archetype.allowed_tools,
    )

    tools = _build_openai_tools(agent)

    messages = [{"role": "system", "content": system_prompt}]
    messages.extend(_history_to_messages(history or []))
    messages.append({"role": "user", "content": user_message})

    full_answer = ""
    evidence_updates: list[dict[str, Any]] = []
    tool_round = 0
    max_tool_rounds = 5

    try:
        while True:
            response = await client.chat.completions.create(
                model=NIPS_MODEL_NAME,
                messages=messages,
                tools=tools if tools else None,
                stream=True,
                temperature=0.8,
            )

            current_tool_calls: dict[int, dict[str, Any]] = {}
            assistant_content = ""

            async for chunk in response:
                delta = chunk.choices[0].delta
                
                # Handle text streaming
                if delta.content:
                    text = delta.content
                    assistant_content += text
                    full_answer += text
                    yield {"type": "assistant_chunk", "text": text}

                # Handle tool call streaming
                if delta.tool_calls:
                    for tc_delta in delta.tool_calls:
                        index = tc_delta.index
                        if index not in current_tool_calls:
                            current_tool_calls[index] = {
                                "id": tc_delta.id,
                                "name": tc_delta.function.name,
                                "arguments": ""
                            }
                        
                        if tc_delta.function.arguments:
                            current_tool_calls[index]["arguments"] += tc_delta.function.arguments

            # If no tool calls, we are done with this turn
            if not current_tool_calls:
                break

            tool_round += 1
            if tool_round > max_tool_rounds:
                yield {"type": "assistant_chunk", "text": "\n\n[Maximum tool rounds reached]"}
                break

            # Add assistant message with tool calls to history
            assistant_msg = {
                "role": "assistant",
                "content": assistant_content or None,
                "tool_calls": [
                    {
                        "id": tc["id"],
                        "type": "function",
                        "function": {
                            "name": tc["name"],
                            "arguments": tc["arguments"]
                        }
                    }
                    for tc in current_tool_calls.values()
                ]
            }
            messages.append(assistant_msg)

            yield {
                "type": "assistant_tool_calls",
                "content": assistant_content or None,
                "tool_calls": assistant_msg["tool_calls"],
            }

            # Execute tool calls
            for tc in current_tool_calls.values():
                tool_name = tc["name"]
                tool_id = tc["id"]
                
                try:
                    tool_args = json.loads(tc["arguments"])
                except Exception:
                    tool_args = {}

                yield {
                    "type": "tool_call_start",
                    "tool": tool_name,
                    "args": tool_args,
                }

                executor = TOOL_EXECUTORS.get(tool_name)
                if not executor:
                    result_text = f"Tool '{tool_name}' not available."
                else:
                    evidence_dicts = [e.model_dump() for e in (known_evidence or [])]
                    for eu in evidence_updates:
                        evidence_dicts.append(eu)

                    kwargs = dict(tool_args)
                    kwargs["evidence"] = evidence_dicts
                    result_text = await executor(**kwargs)

                scored: ScoredOutcome = score_tool_execution(
                    agent,
                    tool_name,
                    result_text,
                    pressure=pressure,
                )

                yield {
                    "type": "tool_call_result",
                    "tool": tool_name,
                    "tool_call_id": tool_id,
                    "preview": result_text[:300],
                    "yield": scored.evidence_yield,
                    "quality": scored.quality,
                    "is_false_positive": scored.is_false_positive,
                    "severity": scored.severity,
                    "latency": scored.latency_seconds,
                }

                if scored.evidence_yield > 0.3:
                    eu = {
                        "node_id": tool_args.get("node_id", "unknown"),
                        "summary": result_text[:200],
                        "details": result_text,
                        "severity": scored.severity,
                        "evidence_type": "log_entry",
                        "confidence": scored.quality,
                        "tags": scored.tags,
                        "agent_instance_id": agent.instance_id,
                        "agent_display_name": agent.display_name,
                        "is_false_positive": scored.is_false_positive,
                    }
                    evidence_updates.append(eu)
                    yield {"type": "evidence_update", **eu}

                # Add tool response to history
                messages.append({
                    "role": "tool",
                    "tool_call_id": tool_id,
                    "name": tool_name,
                    "content": result_text
                })

        yield {
            "type": "done",
            "full_answer": full_answer,
            "evidence_updates": evidence_updates,
            "interaction_id": str(uuid.uuid4()),
        }

    except Exception as exc:
        logger.exception("NIPS chat error for agent %s", agent.instance_id)
        yield {
            "type": "error",
            "message": f"Agent chat failed: {type(exc).__name__}: {str(exc)[:200]}",
        }
