"""Gemini-backed chat orchestration for NIPS agents.

Yields typed event dicts that the Socket.IO router forwards to the client:
  - thought_chunk   : ephemeral reasoning text
  - tool_call_start : tool invocation began
  - tool_call_result: tool finished (with scored output preview)
  - assistant_chunk : final-answer text fragment
  - evidence_update : new evidence generated by a tool
  - done            : stream complete
  - error           : something went wrong
"""

from __future__ import annotations

import logging
import os
import uuid
from typing import Any, AsyncIterator

from google import genai
from google.genai import types as genai_types

from config import GEMINI_API_KEY, NIPS_MODEL_NAME
from nips.archetypes import ARCHETYPES
from nips.models import AgentInstance, ChatMessage, EvidenceUpdate
from nips.prompts import build_system_prompt
from nips.scoring import ScoredOutcome, score_tool_execution
from nips.tools import TOOL_DECLARATION_MAP, TOOL_EXECUTORS

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Gemini client (lazy singleton)
# ---------------------------------------------------------------------------

_client: genai.Client | None = None


def _get_client() -> genai.Client:
    global _client
    if _client is None:
        key = GEMINI_API_KEY
        if not key:
            raise RuntimeError(
                "GEMINI_API_KEY is not set. "
                "Get a key at https://aistudio.google.com/apikey"
            )
        _client = genai.Client(api_key=key)
    return _client


# ---------------------------------------------------------------------------
# Build Gemini tool declarations from archetype
# ---------------------------------------------------------------------------


def _build_tool_declarations(agent: AgentInstance) -> list[genai_types.Tool]:
    """Return a list of google-genai Tool objects for the agent's archetype."""
    archetype = ARCHETYPES[agent.archetype]
    func_decls = []
    for tool_name in archetype.allowed_tools:
        decl = TOOL_DECLARATION_MAP.get(tool_name)
        if not decl:
            continue
        props = decl.get("parameters", {}).get("properties", {})
        required = decl.get("parameters", {}).get("required", [])

        schema_props: dict[str, Any] = {}
        for pname, pdef in props.items():
            prop_schema: dict[str, Any] = {"type": pdef["type"].upper()}
            if "description" in pdef:
                prop_schema["description"] = pdef["description"]
            if "enum" in pdef:
                prop_schema["enum"] = pdef["enum"]
            schema_props[pname] = prop_schema

        func_decls.append(genai_types.FunctionDeclaration(
            name=decl["name"],
            description=decl["description"],
            parameters=genai_types.Schema(
                type="OBJECT",
                properties={
                    k: genai_types.Schema(**v)
                    for k, v in schema_props.items()
                },
                required=required,
            ) if schema_props else None,
        ))

    if not func_decls:
        return []
    return [genai_types.Tool(function_declarations=func_decls)]


# ---------------------------------------------------------------------------
# Convert chat history → Gemini contents
# ---------------------------------------------------------------------------


def _history_to_contents(messages: list[ChatMessage]) -> list[genai_types.Content]:
    """Convert stored chat messages to Gemini Content objects."""
    contents: list[genai_types.Content] = []
    for msg in messages:
        if msg.role == "user":
            contents.append(genai_types.Content(
                role="user",
                parts=[genai_types.Part.from_text(text=msg.content)],
            ))
        elif msg.role == "assistant":
            contents.append(genai_types.Content(
                role="model",
                parts=[genai_types.Part.from_text(text=msg.content)],
            ))
        elif msg.role == "tool" and msg.tool_name:
            contents.append(genai_types.Content(
                role="user",
                parts=[genai_types.Part.from_function_response(
                    name=msg.tool_name,
                    response={"result": msg.content},
                )],
            ))
    return contents


# ---------------------------------------------------------------------------
# Main streaming chat generator
# ---------------------------------------------------------------------------


async def stream_agent_chat(
    agent: AgentInstance,
    user_message: str,
    *,
    history: list[ChatMessage] | None = None,
    case_summary: str = "",
    node_context: str = "",
    known_evidence: list[EvidenceUpdate] | None = None,
    previous_findings: list[str] | None = None,
    funds: int = 0,
    pressure: float = 0.0,
) -> AsyncIterator[dict[str, Any]]:
    """Stream a Gemini chat turn, yielding typed event dicts.

    The caller (Socket.IO router) should forward each yielded dict as a
    separate Socket.IO event.
    """
    client = _get_client()
    archetype = ARCHETYPES[agent.archetype]

    system_prompt = build_system_prompt(
        agent,
        case_summary=case_summary,
        node_context=node_context,
        known_evidence=known_evidence,
        previous_findings=previous_findings,
        funds=funds,
        pressure=pressure,
        allowed_tool_names=archetype.allowed_tools,
    )

    tools = _build_tool_declarations(agent)

    contents = _history_to_contents(history or [])
    contents.append(genai_types.Content(
        role="user",
        parts=[genai_types.Part.from_text(text=user_message)],
    ))

    config = genai_types.GenerateContentConfig(
        system_instruction=system_prompt,
        tools=tools or None,
        thinking_config=genai_types.ThinkingConfig(
            include_thoughts=True,
        ),
        temperature=0.8,
        max_output_tokens=2048,
    )

    full_answer = ""
    thought_buffer = ""
    evidence_updates: list[dict[str, Any]] = []
    tool_round = 0
    max_tool_rounds = 5

    try:
        while True:
            response = client.models.generate_content_stream(
                model=NIPS_MODEL_NAME,
                contents=contents,
                config=config,
            )

            pending_tool_calls: list[dict[str, Any]] = []

            for chunk in response:
                if not chunk.candidates:
                    continue
                candidate = chunk.candidates[0]
                if not candidate.content or not candidate.content.parts:
                    continue

                for part in candidate.content.parts:
                    if hasattr(part, "thought") and part.thought:
                        text = part.text or ""
                        if text:
                            thought_buffer += text
                            yield {"type": "thought_chunk", "text": text}
                        continue

                    if part.function_call:
                        fc = part.function_call
                        tool_name = fc.name
                        tool_args = dict(fc.args) if fc.args else {}

                        yield {
                            "type": "tool_call_start",
                            "tool": tool_name,
                            "args": tool_args,
                        }

                        pending_tool_calls.append({
                            "name": tool_name,
                            "args": tool_args,
                        })
                        continue

                    text = part.text or ""
                    if text:
                        full_answer += text
                        yield {"type": "assistant_chunk", "text": text}

            if not pending_tool_calls:
                break

            tool_round += 1
            if tool_round > max_tool_rounds:
                yield {"type": "assistant_chunk", "text": "\n\n[Maximum tool rounds reached]"}
                break

            model_parts: list[genai_types.Part] = []
            for tc in pending_tool_calls:
                model_parts.append(genai_types.Part.from_function_call(
                    name=tc["name"],
                    args=tc["args"],
                ))
            contents.append(genai_types.Content(role="model", parts=model_parts))

            tool_response_parts: list[genai_types.Part] = []
            for tc in pending_tool_calls:
                executor = TOOL_EXECUTORS.get(tc["name"])
                if not executor:
                    result_text = f"Tool '{tc['name']}' not available."
                else:
                    evidence_dicts = [e.model_dump() for e in (known_evidence or [])]
                    for eu in evidence_updates:
                        evidence_dicts.append(eu)

                    kwargs = dict(tc["args"])
                    kwargs["evidence"] = evidence_dicts
                    result_text = await executor(**kwargs)

                scored: ScoredOutcome = score_tool_execution(
                    agent,
                    tc["name"],
                    result_text,
                    pressure=pressure,
                )

                yield {
                    "type": "tool_call_result",
                    "tool": tc["name"],
                    "preview": result_text[:300],
                    "yield": scored.evidence_yield,
                    "quality": scored.quality,
                    "is_false_positive": scored.is_false_positive,
                    "severity": scored.severity,
                    "latency": scored.latency_seconds,
                }

                if scored.evidence_yield > 0.3:
                    eu = {
                        "node_id": tc["args"].get("node_id", "unknown"),
                        "summary": result_text[:200],
                        "details": result_text,
                        "severity": scored.severity,
                        "evidence_type": "log_entry",
                        "confidence": scored.quality,
                        "tags": scored.tags,
                        "agent_instance_id": agent.instance_id,
                        "agent_display_name": agent.display_name,
                        "is_false_positive": scored.is_false_positive,
                    }
                    evidence_updates.append(eu)
                    yield {"type": "evidence_update", **eu}

                tool_response_parts.append(
                    genai_types.Part.from_function_response(
                        name=tc["name"],
                        response={"result": result_text},
                    )
                )

            contents.append(genai_types.Content(role="user", parts=tool_response_parts))

        yield {
            "type": "done",
            "full_answer": full_answer,
            "evidence_updates": evidence_updates,
            "interaction_id": str(uuid.uuid4()),
        }

    except Exception as exc:
        logger.exception("NIPS chat error for agent %s", agent.instance_id)
        yield {
            "type": "error",
            "message": f"Agent chat failed: {type(exc).__name__}: {str(exc)[:200]}",
        }
