import type { TutorialGuidedAction, TutorialStep } from "./tutorialTypes";

export const GUIDED_TUTORIAL_ACTIONS: TutorialGuidedAction[] = [
  {
    id: "wks03-artifact-sweep",
    nodeId: "WKS-03",
    agentId: "filer",
    label: "Load FILER prompt: inspect the USB artifacts",
    detail:
      "This preloads the real dispatch box with the right starter instruction.",
    instruction:
      "inspect the suspicious USB artifact and credential dumping tool on this node",
  },
  {
    id: "mail01-log-sweep",
    nodeId: "MAIL-01",
    agentId: "logis",
    label: "Load LOGIS prompt: review the auth trail",
    detail:
      "This sets up the real log-analysis task for the relay login chain.",
    instruction: "review the auth logs for stolen login activity on this node",
  },
  {
    id: "mail01-pivot-trace",
    nodeId: "MAIL-01",
    agentId: "nexus",
    label: "Load NEXUS prompt: trace the pivot path",
    detail:
      "This prepares the real network-tracing task that proves lateral movement.",
    instruction: "trace how the attacker moved through this relay node",
  },
  {
    id: "backup01-recover-archive",
    nodeId: "BACKUP-01",
    agentId: "filer",
    label: "Load FILER prompt: recover the staged archive",
    detail:
      "This restores the archive evidence that links the relay to the gateway.",
    instruction: "recover the staged archive file from this relay",
  },
  {
    id: "gw01-trace-egress",
    nodeId: "GW-01",
    agentId: "nexus",
    label: "Load NEXUS prompt: trace the outbound transfer",
    detail: "This prepares the real egress-tracing task for the final handoff.",
    instruction: "trace the outbound exfiltration connection from this node",
  },
  {
    id: "gw01-review-rule",
    nodeId: "GW-01",
    agentId: "logis",
    label: "Load LOGIS prompt: review the gateway rule change",
    detail:
      "This explains why the gateway, not the external host, is the right containment point.",
    instruction: "check the gateway logs for the temporary allow rule",
  },
];

export function getGuidedTutorialActionsForNode(
  nodeId: string | null,
): TutorialGuidedAction[] {
  if (!nodeId) return [];
  return GUIDED_TUTORIAL_ACTIONS.filter((action) => action.nodeId === nodeId);
}

export const GUIDED_TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: "welcome",
    title: "Welcome to the Live Tutorial",
    body: "You are now inside the real investigation shell. The tutorial will coach the actual loop instead of shortcutting it.",
    why: "You will inspect nodes, dispatch agents, earn credits, recruit specialists, resolve issues, and file the winning report through the same interface as a normal case.",
    targetId: null,
    placement: "center",
    completion: { type: "manual" },
    continueLabel: "Enter Tutorial",
  },
  {
    id: "map-overview",
    title: "Read the Investigation Shell",
    body: "The center is the city map, the left feed records evidence and payouts, and the right rail is where you pick systems to inspect.",
    why: "Everything from this point on uses the normal NIPS layout, so the skills carry directly into the full game.",
    targetId: "tutorial-map-shell",
    placement: "top",
    completion: { type: "manual" },
    continueLabel: "Understood",
    highlightPadding: 20,
  },
  {
    id: "select-origin-node",
    title: "Open the First Suspicious Building",
    body: "Click the highlighted workstation in the node list.",
    why: "Tutorial cases start from the earliest suspicious endpoint so you can learn how origin evidence is established.",
    targetId: "tutorial-node-WKS-03",
    placement: "left",
    completion: { type: "selected_node", nodeId: "WKS-03" },
  },
  {
    id: "load-origin-prompt",
    title: "Load the Starter Prompt",
    body: "Click the highlighted FILER suggestion to load the recommended instruction into the real dispatch box.",
    why: "FILER is your starter for this tutorial because artifacts are the fastest way to prove where the incident began.",
    targetId: "tutorial-guided-action-wks03-artifact-sweep",
    placement: "left",
    completion: { type: "manual" },
  },
  {
    id: "inspect-origin-artifacts",
    title: "Dispatch the Real Task",
    body: "Send the preloaded FILER instruction.",
    why: "The tutorial can coach the wording, but the investigation only advances when you use the actual dispatch control.",
    targetId: "tutorial-dispatch-button",
    placement: "left",
    completion: { type: "finding", evidenceKey: "WKS-03:inspect_artifacts" },
    blockerHint:
      "If the button is dim, wait for FILER to return to idle. The field coach will explain what the agent is doing while you wait.",
  },
  {
    id: "review-origin-evidence",
    title: "Read What That Means",
    body: "The recovered script confirms the breach began on WKS-03.",
    why: "Origin evidence tells you where the attack started, not where it merely passed through.",
    targetId: "tutorial-node-inspector",
    placement: "left",
    completion: { type: "manual" },
    continueLabel: "Continue",
  },
  {
    id: "resolve-origin-issue",
    title: "Stabilize the First Issue",
    body: "Resolve the workstation issue with FILER.",
    why: "Issue resolution is your first real containment decision. It turns evidence into action and unlocks the next part of the case.",
    targetId: "tutorial-issue-resolve-wks03_credential_source",
    placement: "left",
    completion: { type: "issue_resolved", issueId: "wks03_credential_source" },
    blockerHint:
      "If the button is dim for a moment, FILER is still finishing the last report.",
  },
  {
    id: "open-market-logis",
    title: "Open the Live Agent Market",
    body: "Use the Market button in the top bar.",
    why: "You earned credits from confirmed evidence. Now you can expand the team through the same recruiting flow used in a normal run.",
    targetId: "tutorial-topbar-market",
    placement: "bottom",
    completion: { type: "manual" },
  },
  {
    id: "recruit-logis",
    title: "Recruit LOGIS",
    body: "Hire LOGIS from the market.",
    why: "The next node needs log analysis, so this is where you grow beyond your starter specialist.",
    targetId: "tutorial-market-buy-logis",
    placement: "bottom",
    completion: { type: "manual" },
  },
  {
    id: "close-market-logis",
    title: "Return to the Investigation",
    body: "Close the market and go back to the map.",
    why: "Recruiting changes your roster, but the evidence work still happens in the main investigation shell.",
    targetId: "tutorial-market-close",
    placement: "bottom",
    completion: { type: "manual" },
  },
  {
    id: "select-mail-node",
    title: "Move to the Pivot System",
    body: "Click the highlighted relay server next.",
    why: "After proving the origin, the next question is how the attack crossed into the rest of the network.",
    targetId: "tutorial-node-MAIL-01",
    placement: "left",
    completion: { type: "selected_node", nodeId: "MAIL-01" },
  },
  {
    id: "load-mail-log-prompt",
    title: "Load the LOGIS Prompt",
    body: "Click the highlighted suggestion to preload the MAIL-01 log-analysis command.",
    why: "LOGIS is the right specialist when you need proof of suspicious access.",
    targetId: "tutorial-guided-action-mail01-log-sweep",
    placement: "left",
    completion: { type: "manual" },
  },
  {
    id: "check-mail-logs",
    title: "Dispatch LOGIS",
    body: "Send the real LOGIS task from the dispatch box.",
    why: "This confirms the stolen account was replayed through the relay.",
    targetId: "tutorial-dispatch-button",
    placement: "left",
    completion: { type: "finding", evidenceKey: "MAIL-01:analyze_logs" },
  },
  {
    id: "open-market-nexus",
    title: "Recruit the Network Specialist",
    body: "Open the market again.",
    why: "You now have enough credits to add NEXUS, the specialist for movement and exfiltration.",
    targetId: "tutorial-topbar-market",
    placement: "bottom",
    completion: { type: "manual" },
  },
  {
    id: "recruit-nexus",
    title: "Recruit NEXUS",
    body: "Hire NEXUS from the market.",
    why: "The next task is a path-tracing job, so you need the network specialist in your live roster.",
    targetId: "tutorial-market-buy-nexus",
    placement: "bottom",
    completion: { type: "manual" },
  },
  {
    id: "close-market-nexus",
    title: "Close the Market Again",
    body: "Return to the investigation shell.",
    why: "The market gives you more tools. The node inspector is where you use them.",
    targetId: "tutorial-market-close",
    placement: "bottom",
    completion: { type: "manual" },
  },
  {
    id: "load-mail-pivot-prompt",
    title: "Load the NEXUS Prompt",
    body: "Click the NEXUS suggestion on MAIL-01.",
    why: "This prepares the movement-tracing instruction in the real dispatch box.",
    targetId: "tutorial-guided-action-mail01-pivot-trace",
    placement: "left",
    completion: { type: "manual" },
  },
  {
    id: "trace-mail-pivot",
    title: "Dispatch NEXUS",
    body: "Send the NEXUS task now.",
    why: "This shows how the attacker moved from the origin into the relay chain.",
    targetId: "tutorial-dispatch-button",
    placement: "left",
    completion: {
      type: "finding",
      evidenceKey: "MAIL-01:trace_lateral_movement",
    },
  },
  {
    id: "resolve-mail-issue",
    title: "Contain the Relay Pivot",
    body: "Resolve the MAIL-01 issue while NEXUS is selected.",
    why: "A correct midgame resolution requires the right evidence and the right specialist role.",
    targetId: "tutorial-issue-resolve-mail01_pivot_containment",
    placement: "left",
    completion: { type: "issue_resolved", issueId: "mail01_pivot_containment" },
  },
  {
    id: "select-backup-node",
    title: "Follow the Staging Relay",
    body: "Click the highlighted backup relay.",
    why: "The chain is not complete until you find where the stolen archive paused before leaving the network.",
    targetId: "tutorial-node-BACKUP-01",
    placement: "left",
    completion: { type: "selected_node", nodeId: "BACKUP-01" },
  },
  {
    id: "load-staging-prompt",
    title: "Load the Archive Recovery Prompt",
    body: "Click the FILER suggestion on BACKUP-01.",
    why: "This prepares the artifact-recovery step that proves the staging relay.",
    targetId: "tutorial-guided-action-backup01-recover-archive",
    placement: "left",
    completion: { type: "manual" },
  },
  {
    id: "recover-staging-file",
    title: "Dispatch FILER",
    body: "Send the archive recovery task.",
    why: "This restores the staged bundle and teaches how artifact recovery supports the attack path, not just the origin.",
    targetId: "tutorial-dispatch-button",
    placement: "left",
    completion: { type: "finding", evidenceKey: "BACKUP-01:recover_files" },
  },
  {
    id: "select-gateway-node",
    title: "Inspect the Final Hop",
    body: "Click the gateway node to prepare the last containment step.",
    why: "The gateway is where you prove and stop the live egress path.",
    targetId: "tutorial-node-GW-01",
    placement: "left",
    completion: { type: "selected_node", nodeId: "GW-01" },
  },
  {
    id: "load-gateway-egress-prompt",
    title: "Load the NEXUS Egress Prompt",
    body: "Click the highlighted NEXUS suggestion on GW-01.",
    why: "This prepares the real egress-tracing instruction in the dispatch box.",
    targetId: "tutorial-guided-action-gw01-trace-egress",
    placement: "left",
    completion: { type: "manual" },
  },
  {
    id: "trace-gateway-egress",
    title: "Dispatch NEXUS",
    body: "Send the outbound-trace task.",
    why: "This confirms the final exfiltration hop under defender control.",
    targetId: "tutorial-dispatch-button",
    placement: "left",
    completion: { type: "finding", evidenceKey: "GW-01:trace_connections" },
  },
  {
    id: "load-gateway-log-prompt",
    title: "Load the LOGIS Gateway Prompt",
    body: "Now click the LOGIS suggestion on the same node.",
    why: "Final reports are stronger when they explain both the path and the enabling control failure.",
    targetId: "tutorial-guided-action-gw01-review-rule",
    placement: "left",
    completion: { type: "manual" },
  },
  {
    id: "review-gateway-logs",
    title: "Dispatch LOGIS",
    body: "Send the gateway log-analysis task.",
    why: "This explains why the gateway is the correct place to stabilize the attack.",
    targetId: "tutorial-dispatch-button",
    placement: "left",
    completion: { type: "finding", evidenceKey: "GW-01:analyze_logs" },
  },
  {
    id: "reselect-nexus-for-gateway-issue",
    title: "Switch Back to NEXUS",
    body: "Select NEXUS again before resolving the gateway issue.",
    why: "LOGIS explains the rule failure, but the actual containment action still belongs to the network specialist.",
    targetId: "tutorial-agent-select-nexus",
    placement: "left",
    completion: { type: "manual" },
  },
  {
    id: "resolve-gateway-issue",
    title: "Block the Live Egress Path",
    body: "Resolve the gateway issue to stabilize the incident.",
    why: "Once the gateway is contained and the full chain is evidenced, the final report phase unlocks.",
    targetId: "tutorial-issue-resolve-gw01_block_egress",
    placement: "left",
    completion: { type: "issue_resolved", issueId: "gw01_block_egress" },
    blockerHint:
      "The final report only opens after this gateway containment step is confirmed.",
  },
  {
    id: "open-final-report",
    title: "Enter the Final Report Phase",
    body: "Open the highlighted Final Report button in the top bar.",
    why: "This is the endgame: you now turn the evidence chain into a formal accusation and mitigation plan.",
    targetId: "tutorial-open-final-report",
    placement: "bottom",
    completion: { type: "final_report_open" },
  },
  {
    id: "choose-origin",
    title: "Choose the Origin Node",
    body: "Set the origin to WKS-03.",
    why: "The credential script on the workstation made it the earliest confirmed compromised node.",
    targetId: "tutorial-final-origin-WKS-03",
    placement: "left",
    completion: { type: "final_report_origin", nodeId: "WKS-03" },
  },
  {
    id: "path-wks03",
    title: "Build the Attack Path",
    body: "Start the path with WKS-03.",
    why: "Ordered paths should begin where the incident truly started.",
    targetId: "tutorial-final-path-WKS-03",
    placement: "left",
    completion: { type: "attack_path_prefix", path: ["WKS-03"] },
  },
  {
    id: "path-mail01",
    title: "Add the Pivot",
    body: "Add MAIL-01 next.",
    why: "This node bridged the origin into the relay chain.",
    targetId: "tutorial-final-path-MAIL-01",
    placement: "left",
    completion: { type: "attack_path_prefix", path: ["WKS-03", "MAIL-01"] },
  },
  {
    id: "path-backup01",
    title: "Add the Staging Relay",
    body: "Add BACKUP-01 as the next hop.",
    why: "The recovered archive proved the theft paused here before leaving the network.",
    targetId: "tutorial-final-path-BACKUP-01",
    placement: "left",
    completion: {
      type: "attack_path_prefix",
      path: ["WKS-03", "MAIL-01", "BACKUP-01"],
    },
  },
  {
    id: "path-gw01",
    title: "Add the Gateway",
    body: "Add GW-01 after the relay.",
    why: "This is the final internal node under defender control.",
    targetId: "tutorial-final-path-GW-01",
    placement: "left",
    completion: {
      type: "attack_path_prefix",
      path: ["WKS-03", "MAIL-01", "BACKUP-01", "GW-01"],
    },
  },
  {
    id: "path-ext01",
    title: "Finish the Path",
    body: "Add the external drop as the final node.",
    why: "The final path should show where the archive ended up after crossing the gateway.",
    targetId: "tutorial-final-path-EXT-01",
    placement: "left",
    completion: {
      type: "attack_path_prefix",
      path: ["WKS-03", "MAIL-01", "BACKUP-01", "GW-01", "EXT-01"],
    },
  },
  {
    id: "choose-attack-type",
    title: "Select the Attack Type",
    body: "Choose data exfiltration.",
    why: "The evidence chain shows theft and transfer of files, not a disruptive-only compromise.",
    targetId: "tutorial-final-attack-data_exfil",
    placement: "right",
    completion: { type: "attack_type", attackType: "data_exfil" },
  },
  {
    id: "choose-mitigation-reset",
    title: "Pick the First Containment Step",
    body: "Add reset credentials to the mitigation plan.",
    why: "The breach began with stolen credentials, so the credential chain must be cut.",
    targetId: "tutorial-final-mitigation-reset_credentials",
    placement: "right",
    completion: {
      type: "mitigation_selected",
      mitigation: "reset_credentials",
    },
  },
  {
    id: "choose-mitigation-persistence",
    title: "Remove the Attacker's Foothold",
    body: "Add remove persistence next.",
    why: "The attacker used staged tooling and temporary access that should be cleared before recovery.",
    targetId: "tutorial-final-mitigation-remove_persistence",
    placement: "right",
    completion: {
      type: "mitigation_selected",
      mitigation: "remove_persistence",
    },
  },
  {
    id: "choose-mitigation-egress",
    title: "Block Future Exfiltration",
    body: "Add block external communication to complete the plan.",
    why: "This ensures the same relay path cannot be reused for another transfer.",
    targetId: "tutorial-final-mitigation-block_external_communication",
    placement: "right",
    completion: {
      type: "mitigation_selected",
      mitigation: "block_external_communication",
    },
  },
  {
    id: "submit-final-report",
    title: "Submit the Winning Report",
    body: "Submit the report now.",
    why: "You have the correct origin, full path, attack type, and mitigation plan.",
    targetId: "tutorial-final-submit",
    placement: "right",
    completion: { type: "evaluation_passed" },
  },
  {
    id: "tutorial-victory",
    title: "Tutorial Complete",
    body: "You completed the real NIPS loop from first clue to successful accusation.",
    why: "You are ready to play the full investigation with the same shell, but less guidance and more ambiguity.",
    targetId: null,
    placement: "center",
    completion: { type: "manual" },
    continueLabel: "Finish",
  },
];
